// Interface en français, arabe (RTL) et anglais.
export const LANGS = { fr: 'Français', ar: 'العربية', en: 'English' };

const D = {
  fr: {
    results: 'Résultats', confirm: 'Confirmer', cancel: 'Annuler', close: 'Fermer', previous: 'Précédent', next: 'Suivant', page: 'Page', of: 'sur', rows: 'lignes', perPage: 'par page', required: 'Champ obligatoire', invalidValue: 'Valeur invalide', invalidMsisdn: 'Numéro tunisien invalide (8 chiffres, +216 facultatif)', percentRange: 'Entre 0 et 100', positiveAmount: 'Montant strictement positif', minLength: 'Au moins {n} caractères', edit: 'Modifier', newVersion: 'Nouvelle version', saving: 'Enregistrement…', skip: 'Aller au contenu', confirmDelete: 'Confirmer la suppression ?', confirmSuspend: 'Suspendre immédiatement ?', confirmRevoke: 'Révoquer définitivement cette clé API ?', confirmStop: 'Désabonner ce numéro ?', confirmApprove: 'Approuver ce tarif ? Il deviendra immuable.', confirmRegulatory: 'Confirmer que l\'autorisation réglementaire est obtenue ?', navLabel: 'Navigation principale', total: 'Total', language: 'Langue', tps: 'Débit max (SMS/s)', prefixes: 'Préfixes MSISDN', comment: 'Commentaire', newPassword: 'Nouveau mot de passe (12 caractères minimum)',
    campaigns: 'Campagnes', billing: 'Facturation', voteOptions: 'Options de vote', voteHint: 'Sans option déclarée, tout texte est accepté ; avec options, seul un code déclaré est compté.', optionCode: 'Code', optionLabel: 'Libellé', quizQuestions: 'Questions du quiz', position: 'Rang', question: 'Question', acceptedAnswers: 'Réponses acceptées (séparées par |)', points: 'Points', replyCorrect: 'Réponse si correct', replyWrong: 'Réponse si faux', contentItems: 'Contenus premium', title: 'Titre', contentBody: 'Texte', maxUses: 'Utilisations max du lien', ttlHours: 'Validité du lien (h)', hourlyTraffic: 'Trafic MO par heure', showTable: 'Afficher le tableau', participants: 'Participants', closed: 'clôturée', closeCampaign: 'Clôturer la campagne', closeHint: 'Ferme le service : plus aucun vote ni réponse n\'est accepté. Irréversible.', confirmCloseCampaign: 'Clôturer définitivement cette campagne ?', changePassword: 'Changer le mot de passe', currentPassword: 'Mot de passe actuel', confirmPassword: 'Confirmer le mot de passe', passwordMismatch: 'Les mots de passe ne correspondent pas', mustChange: 'Votre mot de passe doit être changé avant de continuer.', passwordReconnect: 'Mot de passe changé : reconnectez-vous', sessions: 'Sessions', logoutAll: 'Déconnecter toutes mes sessions', confirmLogoutAll: 'Fermer toutes vos sessions, y compris celle-ci ?', sessionsRevoked: 'Sessions fermées : reconnectez-vous', billingPeriods: 'Périodes clôturées', closePeriod: 'Clôturer la période', closePeriodHint: 'Une période se clôture quand tous ses événements sont rapprochés ; elle est ensuite figée (corrections par ajustement).', confirmClosePeriod: 'Clôturer cette période ? Les écritures seront figées.', invalidRange: 'La date de début doit précéder la date de fin', adjustment: 'Ajustement / remboursement', adjustmentHint: 'Période ouverte : l\'événement passe en REVERSED. Période clôturée : un ajustement négatif est créé.', refund: 'Rembourser', confirmRefund: 'Rembourser cet événement ?', eventId: 'Identifiant d\'événement', reason: 'Motif', statement: 'Relevé partenaire', show: 'Afficher', payouts: 'Reversements', paymentReference: 'Référence de paiement', markPaid: 'Marquer payé', createPayout: 'Créer le reversement', confirmCancelPayout: 'Annuler ce reversement ?',
    app: 'Plateforme VAS', login: 'Connexion', username: 'Utilisateur', password: 'Mot de passe', totp: 'Code MFA (6 chiffres)', logout: 'Déconnexion',
    dashboard: 'Tableau de bord', operators: 'Opérateurs', shortcodes: 'Short codes', services: 'Services', tariffs: 'Tarifs', messages: 'Messages',
    ledger: 'Ledger', reconciliation: 'Rapprochement', rules: 'Listes noire/blanche', support: 'Support', users: 'Utilisateurs', apiClients: 'Clients API',
    partners: 'Partenaires', audit: 'Audit', security: 'Sécurité / MFA', portal: 'Mon portail', save: 'Enregistrer', create: 'Créer', search: 'Rechercher',
    export: 'Exporter', approve: 'Approuver', suspend: 'Suspendre', activate: 'Activer', delete: 'Supprimer', name: 'Nom', status: 'Statut', actions: 'Actions',
    empty: 'Aucune donnée', error: 'Erreur', ok: 'Opération réussie', loading: 'Chargement…', hours: 'Heures', pending: 'MT en attente', deliveryRate: 'Taux de livraison',
    mfaSetup: 'Activer le MFA', mfaSecret: 'Secret TOTP (à saisir dans votre application)', mfaConfirm: 'Confirmer', mfaEnabled: 'MFA actif', estimated: 'Montant estimé',
    reconciled: 'Montant rapproché', file: 'Fichier (CSV / XLSX)', from: 'Du', to: 'Au', simulate: 'Simuler', msisdn: 'MSISDN', keywords: 'Mots-clés', replies: 'Réponses',
    regulatory: 'Approbation réglementaire', forbidden: 'Droits insuffisants', mfaRequired: 'Code MFA requis', devBanner: 'ENVIRONNEMENT DE DÉMONSTRATION — données fictives, mocks actifs', devAccounts: 'Démo : admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'MFA activé : reconnectez-vous avec votre code', badCreds: 'Identifiants invalides',
  },
  en: {
    results: 'Results', confirm: 'Confirm', cancel: 'Cancel', close: 'Close', previous: 'Previous', next: 'Next', page: 'Page', of: 'of', rows: 'rows', perPage: 'per page', required: 'Required field', invalidValue: 'Invalid value', invalidMsisdn: 'Invalid Tunisian number (8 digits, +216 optional)', percentRange: 'Between 0 and 100', positiveAmount: 'Amount must be positive', minLength: 'At least {n} characters', edit: 'Edit', newVersion: 'New version', saving: 'Saving…', skip: 'Skip to content', confirmDelete: 'Confirm deletion?', confirmSuspend: 'Suspend immediately?', confirmRevoke: 'Permanently revoke this API key?', confirmStop: 'Unsubscribe this number?', confirmApprove: 'Approve this tariff? It becomes immutable.', confirmRegulatory: 'Confirm that the regulatory authorisation has been obtained?', navLabel: 'Main navigation', total: 'Total', language: 'Language', tps: 'Max rate (SMS/s)', prefixes: 'MSISDN prefixes', comment: 'Comment', newPassword: 'New password (12 characters minimum)',
    campaigns: 'Campaigns', billing: 'Billing', voteOptions: 'Vote options', voteHint: 'With no declared option any text is accepted; with options only a declared code counts.', optionCode: 'Code', optionLabel: 'Label', quizQuestions: 'Quiz questions', position: 'Rank', question: 'Question', acceptedAnswers: 'Accepted answers (separated by |)', points: 'Points', replyCorrect: 'Reply if correct', replyWrong: 'Reply if wrong', contentItems: 'Premium content', title: 'Title', contentBody: 'Text', maxUses: 'Max link uses', ttlHours: 'Link validity (h)', hourlyTraffic: 'MO traffic per hour', showTable: 'Show table', participants: 'Participants', closed: 'closed', closeCampaign: 'Close campaign', closeHint: 'Closes the service: no more votes or answers are accepted. Irreversible.', confirmCloseCampaign: 'Permanently close this campaign?', changePassword: 'Change password', currentPassword: 'Current password', confirmPassword: 'Confirm password', passwordMismatch: 'Passwords do not match', mustChange: 'Your password must be changed before you continue.', passwordReconnect: 'Password changed: sign in again', sessions: 'Sessions', logoutAll: 'Sign out all my sessions', confirmLogoutAll: 'Close all your sessions, including this one?', sessionsRevoked: 'Sessions closed: sign in again', billingPeriods: 'Closed periods', closePeriod: 'Close period', closePeriodHint: 'A period can be closed once all its events are reconciled; it is then frozen (fix through adjustments).', confirmClosePeriod: 'Close this period? Entries will be frozen.', invalidRange: 'Start must be before end', adjustment: 'Adjustment / refund', adjustmentHint: 'Open period: the event becomes REVERSED. Closed period: a negative adjustment is created.', refund: 'Refund', confirmRefund: 'Refund this event?', eventId: 'Event identifier', reason: 'Reason', statement: 'Partner statement', show: 'Show', payouts: 'Payouts', paymentReference: 'Payment reference', markPaid: 'Mark paid', createPayout: 'Create payout', confirmCancelPayout: 'Cancel this payout?',
    app: 'VAS Platform', login: 'Sign in', username: 'Username', password: 'Password', totp: 'MFA code (6 digits)', logout: 'Sign out',
    dashboard: 'Dashboard', operators: 'Operators', shortcodes: 'Short codes', services: 'Services', tariffs: 'Tariffs', messages: 'Messages',
    ledger: 'Ledger', reconciliation: 'Reconciliation', rules: 'Black/white lists', support: 'Support', users: 'Users', apiClients: 'API clients',
    partners: 'Partners', audit: 'Audit', security: 'Security / MFA', portal: 'My portal', save: 'Save', create: 'Create', search: 'Search',
    export: 'Export', approve: 'Approve', suspend: 'Suspend', activate: 'Activate', delete: 'Delete', name: 'Name', status: 'Status', actions: 'Actions',
    empty: 'No data', error: 'Error', ok: 'Done', loading: 'Loading…', hours: 'Hours', pending: 'Pending MT', deliveryRate: 'Delivery rate',
    mfaSetup: 'Enable MFA', mfaSecret: 'TOTP secret (enter it in your authenticator app)', mfaConfirm: 'Confirm', mfaEnabled: 'MFA enabled', estimated: 'Estimated amount',
    reconciled: 'Reconciled amount', file: 'File (CSV / XLSX)', from: 'From', to: 'To', simulate: 'Simulate', msisdn: 'MSISDN', keywords: 'Keywords', replies: 'Replies',
    regulatory: 'Regulatory approval', forbidden: 'Insufficient rights', mfaRequired: 'MFA code required', devBanner: 'DEMO ENVIRONMENT — fake data, mocks enabled', devAccounts: 'Demo: admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'MFA enabled: sign in again with your code', badCreds: 'Invalid credentials',
  },
  ar: {
    results: 'النتائج', confirm: 'تأكيد', cancel: 'إلغاء', close: 'إغلاق', previous: 'السابق', next: 'التالي', page: 'صفحة', of: 'من', rows: 'سطر', perPage: 'في الصفحة', required: 'حقل إلزامي', invalidValue: 'قيمة غير صالحة', invalidMsisdn: 'رقم تونسي غير صالح (8 أرقام، +216 اختياري)', percentRange: 'بين 0 و100', positiveAmount: 'يجب أن يكون المبلغ موجبا', minLength: '{n} أحرف على الأقل', edit: 'تعديل', newVersion: 'نسخة جديدة', saving: 'جار الحفظ…', skip: 'انتقل إلى المحتوى', confirmDelete: 'تأكيد الحذف؟', confirmSuspend: 'تعليق فوري؟', confirmRevoke: 'إلغاء هذا المفتاح نهائيا؟', confirmStop: 'إلغاء اشتراك هذا الرقم؟', confirmApprove: 'الموافقة على هذه التعريفة؟ ستصبح غير قابلة للتعديل.', confirmRegulatory: 'تأكيد الحصول على الترخيص التنظيمي؟', navLabel: 'التنقل الرئيسي', total: 'المجموع', language: 'اللغة', tps: 'الحد الأقصى (رسالة/ثانية)', prefixes: 'بادئات الأرقام', comment: 'تعليق', newPassword: 'كلمة مرور جديدة (12 حرفا على الأقل)',
    campaigns: 'الحملات', billing: 'الفوترة', voteOptions: 'خيارات التصويت', voteHint: 'بدون خيارات معلنة يُقبل أي نص؛ مع الخيارات يُحتسب الرمز المعلن فقط.', optionCode: 'الرمز', optionLabel: 'التسمية', quizQuestions: 'أسئلة المسابقة', position: 'الترتيب', question: 'السؤال', acceptedAnswers: 'الإجابات المقبولة (مفصولة بـ |)', points: 'النقاط', replyCorrect: 'الرد عند الصواب', replyWrong: 'الرد عند الخطأ', contentItems: 'المحتوى المميز', title: 'العنوان', contentBody: 'النص', maxUses: 'الحد الأقصى لاستخدام الرابط', ttlHours: 'صلاحية الرابط (ساعة)', hourlyTraffic: 'حركة الرسائل الواردة بالساعة', showTable: 'عرض الجدول', participants: 'المشاركون', closed: 'مغلقة', closeCampaign: 'إغلاق الحملة', closeHint: 'يغلق الخدمة: لا تُقبل أصوات أو إجابات بعد ذلك. لا رجعة فيه.', confirmCloseCampaign: 'إغلاق هذه الحملة نهائيا؟', changePassword: 'تغيير كلمة المرور', currentPassword: 'كلمة المرور الحالية', confirmPassword: 'تأكيد كلمة المرور', passwordMismatch: 'كلمتا المرور غير متطابقتين', mustChange: 'يجب تغيير كلمة المرور قبل المتابعة.', passwordReconnect: 'تم تغيير كلمة المرور: سجل الدخول مجددا', sessions: 'الجلسات', logoutAll: 'إنهاء جميع جلساتي', confirmLogoutAll: 'إغلاق جميع جلساتك بما فيها هذه؟', sessionsRevoked: 'تم إغلاق الجلسات: سجل الدخول مجددا', billingPeriods: 'الفترات المغلقة', closePeriod: 'إغلاق الفترة', closePeriodHint: 'تُغلق الفترة عند مطابقة جميع أحداثها؛ ثم تُجمّد (التصحيح بتسويات).', confirmClosePeriod: 'إغلاق هذه الفترة؟ ستُجمّد القيود.', invalidRange: 'يجب أن يسبق تاريخ البداية تاريخ النهاية', adjustment: 'تسوية / استرداد', adjustmentHint: 'فترة مفتوحة: يصبح الحدث REVERSED. فترة مغلقة: تُنشأ تسوية سالبة.', refund: 'استرداد', confirmRefund: 'استرداد هذا الحدث؟', eventId: 'معرف الحدث', reason: 'السبب', statement: 'كشف الشريك', show: 'عرض', payouts: 'التحويلات', paymentReference: 'مرجع الدفع', markPaid: 'تحديد كمدفوع', createPayout: 'إنشاء التحويل', confirmCancelPayout: 'إلغاء هذا التحويل؟',
    app: 'منصة القيمة المضافة', login: 'تسجيل الدخول', username: 'اسم المستخدم', password: 'كلمة المرور', totp: 'رمز التحقق (6 أرقام)', logout: 'خروج',
    dashboard: 'لوحة القيادة', operators: 'المشغلون', shortcodes: 'الأرقام القصيرة', services: 'الخدمات', tariffs: 'التعريفات', messages: 'الرسائل',
    ledger: 'دفتر الفوترة', reconciliation: 'المطابقة', rules: 'القوائم السوداء/البيضاء', support: 'الدعم', users: 'المستخدمون', apiClients: 'عملاء API',
    partners: 'الشركاء', audit: 'التدقيق', security: 'الأمان / التحقق', portal: 'بوابتي', save: 'حفظ', create: 'إنشاء', search: 'بحث',
    export: 'تصدير', approve: 'موافقة', suspend: 'تعليق', activate: 'تفعيل', delete: 'حذف', name: 'الاسم', status: 'الحالة', actions: 'إجراءات',
    empty: 'لا توجد بيانات', error: 'خطأ', ok: 'تمت العملية', loading: 'جار التحميل…', hours: 'ساعات', pending: 'رسائل معلقة', deliveryRate: 'نسبة التسليم',
    mfaSetup: 'تفعيل التحقق بخطوتين', mfaSecret: 'سر TOTP (أدخله في تطبيق المصادقة)', mfaConfirm: 'تأكيد', mfaEnabled: 'التحقق مفعل', estimated: 'المبلغ التقديري',
    reconciled: 'المبلغ المطابق', file: 'ملف (CSV / XLSX)', from: 'من', to: 'إلى', simulate: 'محاكاة', msisdn: 'رقم الهاتف', keywords: 'الكلمات المفتاحية', replies: 'الردود',
    regulatory: 'الموافقة التنظيمية', forbidden: 'صلاحيات غير كافية', mfaRequired: 'رمز التحقق مطلوب', devBanner: 'بيئة تجريبية — بيانات وهمية', devAccounts: 'تجريبي: admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'تم تفعيل التحقق: سجل الدخول مجددا برمزك', badCreds: 'بيانات الدخول غير صحيحة',
  },
};

let lang = (typeof localStorage !== 'undefined' && localStorage.getItem('lang')) || 'fr';
export const getLang = () => lang;
export function setLang(l) {
  lang = l;
  try { localStorage.setItem('lang', l); } catch { /* stockage indisponible */ }
  if (typeof document !== 'undefined') { document.documentElement.lang = l; document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr'; }
}
export const t = (k) => D[lang]?.[k] ?? D.fr[k] ?? k;
export const dict = D;

// Libellés des colonnes de tableaux (clés de données → texte), par langue.
const C = {
  fr: { position: 'Rang', question: 'Question', answers: 'Réponses', points: 'Points', title: 'Titre', maxUses: 'Utilisations max', ttlHours: 'Validité (h)', hour: 'Heure', mo: 'MO', participants: 'Participants', from: 'Du', to: 'Au', closedBy: 'Clôturé par', closedAt: 'Clôturé le', amount: 'Montant', paidBy: 'Payé par', paidAt: 'Payé le', reference: 'Référence', estimatedPartnerShare: 'Part partenaire estimée', label: 'Libellé', partner_: 'Partenaire', id: 'ID', code: 'Code', name: 'Nom', status: 'Statut', maxTps: 'Débit max', dlrBillingRule: 'Règle DLR', msisdnPrefixes: 'Préfixes', number: 'Numéro', operator: 'Opérateur', type: 'Type', shortCode: 'Short code', partner: 'Partenaire', regulated: 'Réglementé', regulatoryApproved: 'Réglem. approuvé', consentMode: 'Consentement', service: 'Service', eventType: 'Événement', grossAmount: 'Prix TTC', operatorPercent: '% opérateur', taxPercent: '% taxes', effectiveFrom: 'Effet', approved: 'Approuvé', createdBy: 'Créé par', createdAt: 'Créé le', msisdn: 'MSISDN', sender: 'Expéditeur', rawStatus: 'Statut brut', segments: 'Segments', attempts: 'Essais', eventId: 'Événement', gross: 'Montant', operatorShare: 'Part opérateur', partnerShare: 'Part partenaire', providerShare: 'Part fournisseur', taxes: 'Taxes', at: 'Date', actor: 'Acteur', action: 'Action', target: 'Cible', detail: 'Détail', username: 'Utilisateur', roles: 'Rôles', active: 'Actif', mfaEnabled: 'MFA', partnerId: 'Partenaire', scopes: 'Droits', rateLimitPerMin: 'Quota/min', word: 'Mot-clé', lang: 'Langue', kind: 'Type', text: 'Texte', operatorAmount: 'Montant opérateur', platformAmount: 'Montant plateforme', result: 'Résultat', comment: 'Commentaire', content: 'Contenu', count: 'Nombre', sharePercent: '% partenaire', webhookUrl: 'Webhook', events: 'Événements', provider: 'Fournisseur', proof: 'Preuve', channel: 'Canal', termsVersion: 'Conditions', reason: 'Motif', opensAt: 'Ouverture', closesAt: 'Fermeture', defaultLang: 'Langue', maxActionsPerMsisdn: 'Max/numéro' },
  en: { position: 'Rank', question: 'Question', answers: 'Answers', points: 'Points', title: 'Title', maxUses: 'Max uses', ttlHours: 'Validity (h)', hour: 'Hour', mo: 'MO', participants: 'Participants', from: 'From', to: 'To', closedBy: 'Closed by', closedAt: 'Closed', amount: 'Amount', paidBy: 'Paid by', paidAt: 'Paid', reference: 'Reference', estimatedPartnerShare: 'Estimated partner share', label: 'Label', partner_: 'Partner', id: 'ID', code: 'Code', name: 'Name', status: 'Status', maxTps: 'Max rate', dlrBillingRule: 'DLR rule', msisdnPrefixes: 'Prefixes', number: 'Number', operator: 'Operator', type: 'Type', shortCode: 'Short code', partner: 'Partner', regulated: 'Regulated', regulatoryApproved: 'Reg. approved', consentMode: 'Consent', service: 'Service', eventType: 'Event', grossAmount: 'Price (incl. tax)', operatorPercent: 'Operator %', taxPercent: 'Tax %', effectiveFrom: 'Effective', approved: 'Approved', createdBy: 'Created by', createdAt: 'Created', msisdn: 'MSISDN', sender: 'Sender', rawStatus: 'Raw status', segments: 'Segments', attempts: 'Attempts', eventId: 'Event', gross: 'Amount', operatorShare: 'Operator share', partnerShare: 'Partner share', providerShare: 'Provider share', taxes: 'Taxes', at: 'Date', actor: 'Actor', action: 'Action', target: 'Target', detail: 'Detail', username: 'User', roles: 'Roles', active: 'Active', mfaEnabled: 'MFA', partnerId: 'Partner', scopes: 'Scopes', rateLimitPerMin: 'Quota/min', word: 'Keyword', lang: 'Language', kind: 'Kind', text: 'Text', operatorAmount: 'Operator amount', platformAmount: 'Platform amount', result: 'Result', comment: 'Comment', content: 'Content', count: 'Count', sharePercent: 'Partner %', webhookUrl: 'Webhook', events: 'Events', provider: 'Provider', proof: 'Proof', channel: 'Channel', termsVersion: 'Terms', reason: 'Reason', opensAt: 'Opens', closesAt: 'Closes', defaultLang: 'Language', maxActionsPerMsisdn: 'Max/number' },
  ar: { position: 'الترتيب', question: 'السؤال', answers: 'الإجابات', points: 'النقاط', title: 'العنوان', maxUses: 'الحد الأقصى', ttlHours: 'الصلاحية (س)', hour: 'الساعة', mo: 'الواردة', participants: 'المشاركون', from: 'من', to: 'إلى', closedBy: 'أغلقه', closedAt: 'تاريخ الإغلاق', amount: 'المبلغ', paidBy: 'دفعه', paidAt: 'تاريخ الدفع', reference: 'المرجع', estimatedPartnerShare: 'حصة الشريك التقديرية', label: 'التسمية', partner_: 'الشريك', id: 'المعرف', code: 'الرمز', name: 'الاسم', status: 'الحالة', maxTps: 'الحد الأقصى', dlrBillingRule: 'قاعدة التسليم', msisdnPrefixes: 'البادئات', number: 'الرقم', operator: 'المشغل', type: 'النوع', shortCode: 'الرقم القصير', partner: 'الشريك', regulated: 'منظم', regulatoryApproved: 'موافقة تنظيمية', consentMode: 'الموافقة', service: 'الخدمة', eventType: 'الحدث', grossAmount: 'السعر شامل الضريبة', operatorPercent: '% المشغل', taxPercent: '% الضريبة', effectiveFrom: 'السريان', approved: 'معتمد', createdBy: 'أنشأه', createdAt: 'تاريخ الإنشاء', msisdn: 'رقم الهاتف', sender: 'المرسل', rawStatus: 'الحالة الخام', segments: 'الأجزاء', attempts: 'المحاولات', eventId: 'الحدث', gross: 'المبلغ', operatorShare: 'حصة المشغل', partnerShare: 'حصة الشريك', providerShare: 'حصة المزود', taxes: 'الضرائب', at: 'التاريخ', actor: 'المنفذ', action: 'الإجراء', target: 'الهدف', detail: 'التفاصيل', username: 'المستخدم', roles: 'الأدوار', active: 'نشط', mfaEnabled: 'التحقق', partnerId: 'الشريك', scopes: 'الصلاحيات', rateLimitPerMin: 'الحصة/دقيقة', word: 'الكلمة المفتاحية', lang: 'اللغة', kind: 'النوع', text: 'النص', operatorAmount: 'مبلغ المشغل', platformAmount: 'مبلغ المنصة', result: 'النتيجة', comment: 'تعليق', content: 'المحتوى', count: 'العدد', sharePercent: '% الشريك', webhookUrl: 'الويب هوك', events: 'الأحداث', provider: 'المزود', proof: 'الإثبات', channel: 'القناة', termsVersion: 'الشروط', reason: 'السبب', opensAt: 'الافتتاح', closesAt: 'الإغلاق', defaultLang: 'اللغة', maxActionsPerMsisdn: 'الحد/رقم' },
};
/** Libellé d'une colonne dans la langue courante (repli : le nom de la clé). */
export const tc = (k) => C[lang]?.[k] ?? C.fr[k] ?? k;
export const colDict = C;
