// Interface en français, arabe (RTL) et anglais.
export const LANGS = { fr: 'Français', ar: 'العربية', en: 'English' };

const D = {
  fr: {
    results: 'Résultats', confirm: 'Confirmer', cancel: 'Annuler', close: 'Fermer', previous: 'Précédent', next: 'Suivant', page: 'Page', of: 'sur', rows: 'lignes', perPage: 'par page', required: 'Champ obligatoire', invalidValue: 'Valeur invalide', invalidMsisdn: 'Numéro tunisien invalide (8 chiffres, +216 facultatif)', percentRange: 'Entre 0 et 100', positiveAmount: 'Montant strictement positif', minLength: 'Au moins {n} caractères', edit: 'Modifier', newVersion: 'Nouvelle version', saving: 'Enregistrement…', skip: 'Aller au contenu', confirmDelete: 'Confirmer la suppression ?', confirmSuspend: 'Suspendre immédiatement ?', confirmRevoke: 'Révoquer définitivement cette clé API ?', confirmStop: 'Désabonner ce numéro ?', confirmApprove: 'Approuver ce tarif ? Il deviendra immuable.', confirmRegulatory: 'Confirmer que l\'autorisation réglementaire est obtenue ?', navLabel: 'Navigation principale', total: 'Total', language: 'Langue', tps: 'Débit max (SMS/s)', prefixes: 'Préfixes MSISDN', comment: 'Commentaire', newPassword: 'Nouveau mot de passe (12 caractères minimum)',
    app: 'Plateforme VAS', login: 'Connexion', username: 'Utilisateur', password: 'Mot de passe', totp: 'Code MFA (6 chiffres)', logout: 'Déconnexion',
    dashboard: 'Tableau de bord', operators: 'Opérateurs', shortcodes: 'Short codes', services: 'Services', tariffs: 'Tarifs', messages: 'Messages',
    ledger: 'Ledger', reconciliation: 'Rapprochement', rules: 'Listes noire/blanche', support: 'Support', users: 'Utilisateurs', apiClients: 'Clients API',
    partners: 'Partenaires', audit: 'Audit', security: 'Sécurité / MFA', portal: 'Mon portail', save: 'Enregistrer', create: 'Créer', search: 'Rechercher',
    export: 'Exporter', approve: 'Approuver', suspend: 'Suspendre', activate: 'Activer', delete: 'Supprimer', name: 'Nom', status: 'Statut', actions: 'Actions',
    empty: 'Aucune donnée', error: 'Erreur', ok: 'Opération réussie', loading: 'Chargement…', hours: 'Heures', pending: 'MT en attente', deliveryRate: 'Taux de livraison',
    mfaSetup: 'Activer le MFA', mfaSecret: 'Secret TOTP (à saisir dans votre application)', mfaConfirm: 'Confirmer', mfaEnabled: 'MFA actif', estimated: 'Montant estimé',
    reconciled: 'Montant rapproché', file: 'Fichier (CSV / XLSX)', from: 'Du', to: 'Au', simulate: 'Simuler', msisdn: 'MSISDN', keywords: 'Mots-clés', replies: 'Réponses',
    regulatory: 'Approbation réglementaire', forbidden: 'Droits insuffisants', mfaRequired: 'Code MFA requis', devBanner: 'ENVIRONNEMENT DE DÉMONSTRATION — données fictives, mocks actifs', devAccounts: 'Démo : admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'MFA activé : reconnectez-vous avec votre code', badCreds: 'Identifiants invalides',
  },
  en: {
    results: 'Results', confirm: 'Confirm', cancel: 'Cancel', close: 'Close', previous: 'Previous', next: 'Next', page: 'Page', of: 'of', rows: 'rows', perPage: 'per page', required: 'Required field', invalidValue: 'Invalid value', invalidMsisdn: 'Invalid Tunisian number (8 digits, +216 optional)', percentRange: 'Between 0 and 100', positiveAmount: 'Amount must be positive', minLength: 'At least {n} characters', edit: 'Edit', newVersion: 'New version', saving: 'Saving…', skip: 'Skip to content', confirmDelete: 'Confirm deletion?', confirmSuspend: 'Suspend immediately?', confirmRevoke: 'Permanently revoke this API key?', confirmStop: 'Unsubscribe this number?', confirmApprove: 'Approve this tariff? It becomes immutable.', confirmRegulatory: 'Confirm that the regulatory authorisation has been obtained?', navLabel: 'Main navigation', total: 'Total', language: 'Language', tps: 'Max rate (SMS/s)', prefixes: 'MSISDN prefixes', comment: 'Comment', newPassword: 'New password (12 characters minimum)',
    app: 'VAS Platform', login: 'Sign in', username: 'Username', password: 'Password', totp: 'MFA code (6 digits)', logout: 'Sign out',
    dashboard: 'Dashboard', operators: 'Operators', shortcodes: 'Short codes', services: 'Services', tariffs: 'Tariffs', messages: 'Messages',
    ledger: 'Ledger', reconciliation: 'Reconciliation', rules: 'Black/white lists', support: 'Support', users: 'Users', apiClients: 'API clients',
    partners: 'Partners', audit: 'Audit', security: 'Security / MFA', portal: 'My portal', save: 'Save', create: 'Create', search: 'Search',
    export: 'Export', approve: 'Approve', suspend: 'Suspend', activate: 'Activate', delete: 'Delete', name: 'Name', status: 'Status', actions: 'Actions',
    empty: 'No data', error: 'Error', ok: 'Done', loading: 'Loading…', hours: 'Hours', pending: 'Pending MT', deliveryRate: 'Delivery rate',
    mfaSetup: 'Enable MFA', mfaSecret: 'TOTP secret (enter it in your authenticator app)', mfaConfirm: 'Confirm', mfaEnabled: 'MFA enabled', estimated: 'Estimated amount',
    reconciled: 'Reconciled amount', file: 'File (CSV / XLSX)', from: 'From', to: 'To', simulate: 'Simulate', msisdn: 'MSISDN', keywords: 'Keywords', replies: 'Replies',
    regulatory: 'Regulatory approval', forbidden: 'Insufficient rights', mfaRequired: 'MFA code required', devBanner: 'DEMO ENVIRONMENT — fake data, mocks enabled', devAccounts: 'Demo: admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'MFA enabled: sign in again with your code', badCreds: 'Invalid credentials',
  },
  ar: {
    results: 'النتائج', confirm: 'تأكيد', cancel: 'إلغاء', close: 'إغلاق', previous: 'السابق', next: 'التالي', page: 'صفحة', of: 'من', rows: 'سطر', perPage: 'في الصفحة', required: 'حقل إلزامي', invalidValue: 'قيمة غير صالحة', invalidMsisdn: 'رقم تونسي غير صالح (8 أرقام، +216 اختياري)', percentRange: 'بين 0 و100', positiveAmount: 'يجب أن يكون المبلغ موجبا', minLength: '{n} أحرف على الأقل', edit: 'تعديل', newVersion: 'نسخة جديدة', saving: 'جار الحفظ…', skip: 'انتقل إلى المحتوى', confirmDelete: 'تأكيد الحذف؟', confirmSuspend: 'تعليق فوري؟', confirmRevoke: 'إلغاء هذا المفتاح نهائيا؟', confirmStop: 'إلغاء اشتراك هذا الرقم؟', confirmApprove: 'الموافقة على هذه التعريفة؟ ستصبح غير قابلة للتعديل.', confirmRegulatory: 'تأكيد الحصول على الترخيص التنظيمي؟', navLabel: 'التنقل الرئيسي', total: 'المجموع', language: 'اللغة', tps: 'الحد الأقصى (رسالة/ثانية)', prefixes: 'بادئات الأرقام', comment: 'تعليق', newPassword: 'كلمة مرور جديدة (12 حرفا على الأقل)',
    app: 'منصة القيمة المضافة', login: 'تسجيل الدخول', username: 'اسم المستخدم', password: 'كلمة المرور', totp: 'رمز التحقق (6 أرقام)', logout: 'خروج',
    dashboard: 'لوحة القيادة', operators: 'المشغلون', shortcodes: 'الأرقام القصيرة', services: 'الخدمات', tariffs: 'التعريفات', messages: 'الرسائل',
    ledger: 'دفتر الفوترة', reconciliation: 'المطابقة', rules: 'القوائم السوداء/البيضاء', support: 'الدعم', users: 'المستخدمون', apiClients: 'عملاء API',
    partners: 'الشركاء', audit: 'التدقيق', security: 'الأمان / التحقق', portal: 'بوابتي', save: 'حفظ', create: 'إنشاء', search: 'بحث',
    export: 'تصدير', approve: 'موافقة', suspend: 'تعليق', activate: 'تفعيل', delete: 'حذف', name: 'الاسم', status: 'الحالة', actions: 'إجراءات',
    empty: 'لا توجد بيانات', error: 'خطأ', ok: 'تمت العملية', loading: 'جار التحميل…', hours: 'ساعات', pending: 'رسائل معلقة', deliveryRate: 'نسبة التسليم',
    mfaSetup: 'تفعيل التحقق بخطوتين', mfaSecret: 'سر TOTP (أدخله في تطبيق المصادقة)', mfaConfirm: 'تأكيد', mfaEnabled: 'التحقق مفعل', estimated: 'المبلغ التقديري',
    reconciled: 'المبلغ المطابق', file: 'ملف (CSV / XLSX)', from: 'من', to: 'إلى', simulate: 'محاكاة', msisdn: 'رقم الهاتف', keywords: 'الكلمات المفتاحية', replies: 'الردود',
    regulatory: 'الموافقة التنظيمية', forbidden: 'صلاحيات غير كافية', mfaRequired: 'رمز التحقق مطلوب', devBanner: 'بيئة تجريبية — بيانات وهمية', devAccounts: 'تجريبي: admin / Admin-dev-pass1 · manager, noc, finance, finance2, support, auditor, club / Dev-pass-12345', mfaReconnect: 'تم تفعيل التحقق: سجل الدخول مجددا برمزك', badCreds: 'بيانات الدخول غير صحيحة',
  },
};

let lang = (typeof localStorage !== 'undefined' && localStorage.getItem('lang')) || 'fr';
export const getLang = () => lang;
export function setLang(l) {
  lang = l;
  try { localStorage.setItem('lang', l); } catch { /* stockage indisponible */ }
  if (typeof document !== 'undefined') { document.documentElement.lang = l; document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr'; }
}
export const t = (k) => D[lang]?.[k] ?? D.fr[k] ?? k;
export const dict = D;

// Libellés des colonnes de tableaux (clés de données → texte), par langue.
const C = {
  fr: { id: 'ID', code: 'Code', name: 'Nom', status: 'Statut', maxTps: 'Débit max', dlrBillingRule: 'Règle DLR', msisdnPrefixes: 'Préfixes', number: 'Numéro', operator: 'Opérateur', type: 'Type', shortCode: 'Short code', partner: 'Partenaire', regulated: 'Réglementé', regulatoryApproved: 'Réglem. approuvé', consentMode: 'Consentement', service: 'Service', eventType: 'Événement', grossAmount: 'Prix TTC', operatorPercent: '% opérateur', taxPercent: '% taxes', effectiveFrom: 'Effet', approved: 'Approuvé', createdBy: 'Créé par', createdAt: 'Créé le', msisdn: 'MSISDN', sender: 'Expéditeur', rawStatus: 'Statut brut', segments: 'Segments', attempts: 'Essais', eventId: 'Événement', gross: 'Montant', operatorShare: 'Part opérateur', partnerShare: 'Part partenaire', providerShare: 'Part fournisseur', taxes: 'Taxes', at: 'Date', actor: 'Acteur', action: 'Action', target: 'Cible', detail: 'Détail', username: 'Utilisateur', roles: 'Rôles', active: 'Actif', mfaEnabled: 'MFA', partnerId: 'Partenaire', scopes: 'Droits', rateLimitPerMin: 'Quota/min', word: 'Mot-clé', lang: 'Langue', kind: 'Type', text: 'Texte', operatorAmount: 'Montant opérateur', platformAmount: 'Montant plateforme', result: 'Résultat', comment: 'Commentaire', content: 'Contenu', count: 'Nombre', sharePercent: '% partenaire', webhookUrl: 'Webhook', events: 'Événements', provider: 'Fournisseur', proof: 'Preuve', channel: 'Canal', termsVersion: 'Conditions', reason: 'Motif', opensAt: 'Ouverture', closesAt: 'Fermeture', defaultLang: 'Langue', maxActionsPerMsisdn: 'Max/numéro' },
  en: { id: 'ID', code: 'Code', name: 'Name', status: 'Status', maxTps: 'Max rate', dlrBillingRule: 'DLR rule', msisdnPrefixes: 'Prefixes', number: 'Number', operator: 'Operator', type: 'Type', shortCode: 'Short code', partner: 'Partner', regulated: 'Regulated', regulatoryApproved: 'Reg. approved', consentMode: 'Consent', service: 'Service', eventType: 'Event', grossAmount: 'Price (incl. tax)', operatorPercent: 'Operator %', taxPercent: 'Tax %', effectiveFrom: 'Effective', approved: 'Approved', createdBy: 'Created by', createdAt: 'Created', msisdn: 'MSISDN', sender: 'Sender', rawStatus: 'Raw status', segments: 'Segments', attempts: 'Attempts', eventId: 'Event', gross: 'Amount', operatorShare: 'Operator share', partnerShare: 'Partner share', providerShare: 'Provider share', taxes: 'Taxes', at: 'Date', actor: 'Actor', action: 'Action', target: 'Target', detail: 'Detail', username: 'User', roles: 'Roles', active: 'Active', mfaEnabled: 'MFA', partnerId: 'Partner', scopes: 'Scopes', rateLimitPerMin: 'Quota/min', word: 'Keyword', lang: 'Language', kind: 'Kind', text: 'Text', operatorAmount: 'Operator amount', platformAmount: 'Platform amount', result: 'Result', comment: 'Comment', content: 'Content', count: 'Count', sharePercent: 'Partner %', webhookUrl: 'Webhook', events: 'Events', provider: 'Provider', proof: 'Proof', channel: 'Channel', termsVersion: 'Terms', reason: 'Reason', opensAt: 'Opens', closesAt: 'Closes', defaultLang: 'Language', maxActionsPerMsisdn: 'Max/number' },
  ar: { id: 'المعرف', code: 'الرمز', name: 'الاسم', status: 'الحالة', maxTps: 'الحد الأقصى', dlrBillingRule: 'قاعدة التسليم', msisdnPrefixes: 'البادئات', number: 'الرقم', operator: 'المشغل', type: 'النوع', shortCode: 'الرقم القصير', partner: 'الشريك', regulated: 'منظم', regulatoryApproved: 'موافقة تنظيمية', consentMode: 'الموافقة', service: 'الخدمة', eventType: 'الحدث', grossAmount: 'السعر شامل الضريبة', operatorPercent: '% المشغل', taxPercent: '% الضريبة', effectiveFrom: 'السريان', approved: 'معتمد', createdBy: 'أنشأه', createdAt: 'تاريخ الإنشاء', msisdn: 'رقم الهاتف', sender: 'المرسل', rawStatus: 'الحالة الخام', segments: 'الأجزاء', attempts: 'المحاولات', eventId: 'الحدث', gross: 'المبلغ', operatorShare: 'حصة المشغل', partnerShare: 'حصة الشريك', providerShare: 'حصة المزود', taxes: 'الضرائب', at: 'التاريخ', actor: 'المنفذ', action: 'الإجراء', target: 'الهدف', detail: 'التفاصيل', username: 'المستخدم', roles: 'الأدوار', active: 'نشط', mfaEnabled: 'التحقق', partnerId: 'الشريك', scopes: 'الصلاحيات', rateLimitPerMin: 'الحصة/دقيقة', word: 'الكلمة المفتاحية', lang: 'اللغة', kind: 'النوع', text: 'النص', operatorAmount: 'مبلغ المشغل', platformAmount: 'مبلغ المنصة', result: 'النتيجة', comment: 'تعليق', content: 'المحتوى', count: 'العدد', sharePercent: '% الشريك', webhookUrl: 'الويب هوك', events: 'الأحداث', provider: 'المزود', proof: 'الإثبات', channel: 'القناة', termsVersion: 'الشروط', reason: 'السبب', opensAt: 'الافتتاح', closesAt: 'الإغلاق', defaultLang: 'اللغة', maxActionsPerMsisdn: 'الحد/رقم' },
};
/** Libellé d'une colonne dans la langue courante (repli : le nom de la clé). */
export const tc = (k) => C[lang]?.[k] ?? C.fr[k] ?? k;
export const colDict = C;
