-- Routage MT sans service : plages de numéros (plus long préfixe) et numéros portés (exception exacte, prioritaire)
CREATE TABLE number_range (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prefix VARCHAR(12) NOT NULL UNIQUE,
  operator_id BIGINT NOT NULL REFERENCES operator(id),
  source VARCHAR(60),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE ported_number (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msisdn VARCHAR(100) NOT NULL UNIQUE,
  operator_id BIGINT NOT NULL REFERENCES operator(id),
  source VARCHAR(60),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
