CREATE TABLE msisdn_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  msisdn VARCHAR(20) NOT NULL,
  service_id BIGINT REFERENCES vas_service(id),
  rule_type VARCHAR(10) NOT NULL,
  reason VARCHAR(200),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_rule_msisdn ON msisdn_rule(msisdn);
