-- Quiz à questions successives, contenus premium à lien jeton, choix de vote valides, clôture de campagne
ALTER TABLE vas_service ADD COLUMN closed_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE quiz_question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES vas_service(id),
  position INT NOT NULL,
  question VARCHAR(500) NOT NULL,
  answers VARCHAR(300) NOT NULL,
  points INT NOT NULL DEFAULT 1,
  reply_correct VARCHAR(300),
  reply_wrong VARCHAR(300),
  CONSTRAINT uq_quiz_pos UNIQUE (service_id, position)
);
CREATE TABLE quiz_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES vas_service(id),
  msisdn VARCHAR(100) NOT NULL,
  current_position INT NOT NULL,
  score INT NOT NULL DEFAULT 0,
  status VARCHAR(12) NOT NULL,
  started_at TIMESTAMP WITH TIME ZONE NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uq_quiz_progress UNIQUE (service_id, msisdn)
);
CREATE INDEX ix_quiz_progress_rank ON quiz_progress (service_id, status, score);

CREATE TABLE content_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES vas_service(id),
  code VARCHAR(40) NOT NULL,
  title VARCHAR(120) NOT NULL,
  body VARCHAR(2000),
  url VARCHAR(400),
  max_uses INT NOT NULL DEFAULT 1,
  ttl_hours INT NOT NULL DEFAULT 24,
  CONSTRAINT uq_content_code UNIQUE (service_id, code)
);
CREATE TABLE content_token (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(64) NOT NULL UNIQUE,
  item_id BIGINT NOT NULL REFERENCES content_item(id),
  msisdn VARCHAR(100) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  uses INT NOT NULL DEFAULT 0
);
CREATE INDEX ix_content_token_item ON content_token (item_id);

CREATE TABLE vote_option (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES vas_service(id),
  code VARCHAR(40) NOT NULL,
  label VARCHAR(120) NOT NULL,
  CONSTRAINT uq_vote_option UNIQUE (service_id, code)
);
CREATE TABLE vote_ballot (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_id BIGINT NOT NULL REFERENCES vas_service(id),
  msisdn VARCHAR(100) NOT NULL,
  option_code VARCHAR(40) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  mo_id BIGINT
);
CREATE INDEX ix_ballot_service_option ON vote_ballot (service_id, option_code);
CREATE INDEX ix_ballot_service_msisdn ON vote_ballot (service_id, msisdn);
