-- 10. abonnements : échecs de renouvellement, lien MT -> abonnement
ALTER TABLE subscription ADD COLUMN renewal_failures INT NOT NULL DEFAULT 0;
ALTER TABLE mt_message ADD COLUMN subscription_id BIGINT;
-- 11. débits par service et par partenaire (0 = illimité)
ALTER TABLE vas_service ADD COLUMN max_tps INT NOT NULL DEFAULT 0;
ALTER TABLE partner ADD COLUMN max_tps INT NOT NULL DEFAULT 0;
-- 12. envoi programmé
ALTER TABLE mt_message ADD COLUMN scheduled_at TIMESTAMP WITH TIME ZONE;
CREATE INDEX ix_mt_scheduled ON mt_message (status, scheduled_at);
-- 13. clôture de période et reversements
CREATE TABLE billing_period (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_at TIMESTAMP WITH TIME ZONE NOT NULL,
  to_at TIMESTAMP WITH TIME ZONE NOT NULL,
  closed_at TIMESTAMP WITH TIME ZONE NOT NULL,
  closed_by VARCHAR(80) NOT NULL,
  events INT NOT NULL,
  gross DECIMAL(14,3) NOT NULL,
  operator_share DECIMAL(14,3) NOT NULL,
  partner_share DECIMAL(14,3) NOT NULL,
  provider_share DECIMAL(14,3) NOT NULL,
  taxes DECIMAL(14,3) NOT NULL,
  CONSTRAINT uq_period UNIQUE (from_at, to_at)
);
CREATE TABLE partner_payout (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id BIGINT NOT NULL REFERENCES partner(id),
  from_at TIMESTAMP WITH TIME ZONE NOT NULL,
  to_at TIMESTAMP WITH TIME ZONE NOT NULL,
  amount DECIMAL(14,3) NOT NULL,
  status VARCHAR(10) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by VARCHAR(80) NOT NULL,
  paid_at TIMESTAMP WITH TIME ZONE,
  paid_by VARCHAR(80),
  reference VARCHAR(100)
);
CREATE INDEX ix_payout_partner ON partner_payout (partner_id, from_at, to_at);
-- 15. comptes : changement de mot de passe imposé, révocation des sessions
ALTER TABLE app_user ADD COLUMN must_change_password BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE app_user ADD COLUMN token_version INT NOT NULL DEFAULT 0;
-- 15. chiffrement des numéros au repos (déterministe) : colonnes élargies pour "enc:v1:<base64>"
ALTER TABLE mo_message ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
ALTER TABLE mt_message ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
ALTER TABLE subscription ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
ALTER TABLE consent_record ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
ALTER TABLE ledger_event ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
ALTER TABLE msisdn_rule ALTER COLUMN msisdn SET DATA TYPE VARCHAR(100);
